// github.com/mikhail5545/media-service-go
// microservice for vitianmove project family
// Copyright (C) 2025  Mikhail Kulik

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Package asset provides models, DTO models for [cloudinary.Service] requests and validation tools.
package asset

import (
	"time"

	"gorm.io/gorm"
)

type Asset struct {
	ID                 string         `gorm:"primaryKey;size:36" json:"id"` // Internal ID (uuid), generated at instance creation
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	DeletedAt          gorm.DeletedAt `json:"deleted_at"`
	CloudinaryAssetID  string         `json:"cloudinary_asset_id"` // External ID (cloudinary ID), parsed from webhooks
	URL                string         `json:"url"`
	SecureURL          string         `json:"secure_url"`
	CloudinaryPublicID string         `json:"cloudinary_public_id"` // External ID (cloudniary public ID for asset), used in most of Cloudinary API interactions
	ResourceType       string         `gorm:"varchar(128)" json:"resource_type"`
	Format             string         `gorm:"varchar(32)" json:"format"`        // Asset format (png, jpeg, jpc, etc.), parsed from webhooks
	Width              *int           `gorm:"null" json:"width"`                // Width for images, parsed from webhooks
	Height             *int           `gorm:"null" json:"height"`               // Height for images, parsed from webhooks
	Tags               []string       `gorm:"type:varchar(128)[]" json:"tags"`  // Tags, generated by Cloudinary
	AssetFolder        string         `gorm:"varchar(128)" json:"asset_folder"` // Asset folder in the Cloudinary, parsed from webhooks
	DisplayName        string         `gorm:"varchar(255)" json:"display_name"` // Asset's display name, parsed from webhooks
}
