package asset

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type Status string

const (
	StatusActive   Status = "active"
	StatusArchived Status = "archived"
	StatusBroken   Status = "broken"
)

type Asset struct {
	ID        uuid.UUID      `gorm:"primaryKey;type:uuid" json:"id"` // UUIDv7
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"index" json:"deleted_at"`

	Status Status `gorm:"type:varchar(32);default:'active'" json:"status"`

	CloudinaryAssetID  string   `json:"cloudinary_asset_id"` // External ID (Cloudinary ID), parsed from webhooks
	URL                string   `json:"url"`
	SecureURL          string   `json:"secure_url"`
	CloudinaryPublicID string   `json:"cloudinary_public_id"` // External ID (Cloudinary public ID for asset), used in most of Cloudinary API interactions
	ResourceType       string   `gorm:"type:varchar(128)" json:"resource_type"`
	Format             string   `gorm:"type:varchar(32)" json:"format"`   // Asset format (png, jpeg, jpc, etc.), parsed from webhooks
	Width              *int     `gorm:"null" json:"width"`                // Width for images, parsed from webhooks
	Height             *int     `gorm:"null" json:"height"`               // Height for images, parsed from webhooks
	Tags               []string `gorm:"type:varchar(128)[]" json:"tags"`  // Tags, generated by Cloudinary
	AssetFolder        string   `gorm:"varchar(128)" json:"asset_folder"` // Asset folder in the Cloudinary, parsed from webhooks
	DisplayName        string   `gorm:"varchar(255)" json:"display_name"` // Asset's display name, parsed from webhooks
}

func (*Asset) TableName() string {
	return "cloudinary_assets"
}

func (a *Asset) BeforeCreate(tx *gorm.DB) (err error) {
	if a.ID == uuid.Nil {
		a.ID, err = uuid.NewV7()
		if err != nil {
			return err
		}
	}
	return nil
}
